name: CI - Build and Test

on:
  push:
    branches:
      - arreglosCole

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos a Gradle
        run: chmod +x ./gradlew

      - name: Construcción del proyecto (.jar)
        run: |
          ./gradlew build 
          echo "Construcción realizada por: solmunjim"

      - name: Ejecutar los tests
        run: |
          ./gradlew test 
          echo "Tests ejecutados por: solmunjim"
